export enum Fee {

  REGISTRATIONOFDESIGNSTEXTILE = "REGISTRATION OF DESIGNS (TEXTILE)"  ,
  REGISTRATIONOFDESIGNSNONTEXTILE = "REGISTRATION OF DESIGNS (NON- TEXTILES)"  ,
  REGISTRATIONOFPATENTNONCONVENTIONAL ="REGISTRATION OF PATENT (NON-CONVENTIONAL)" ,
  REGISTRATIONOFPATENTCONVENTIONAL ="REGISTRATION OF PATENT (CONVENTIONAL)"
   ,




  }
