export enum Fee {

  REGISTRATIONOFDESIGNSTEXTILE = "REGISTRATION OF DESIGNS (TEXTILE)"  ,
  REGISTRATIONOFDESIGNSNONTEXTILE = "REGISTRATION OF DESIGNS (NON- TEXTILES)"  ,
  REGISTRATIONOFPATENTNONCONVENTIONAL ="REGISTRATION OF PATENT (NON-CONVENTIONAL)" ,
  REGISTRATIONOFPATENTCONVENTIONAL ="REGISTRATION OF PATENT (CONVENTIONAL)",
  PRELIMINARYSEARCHREPORT ="PRELIMINARY SEARCH REPORT" ,
  APPLICATIONFORREGISTRATIONOFTRADESERVICE ="APPLICATION FOR REGISTRATION OF TRADE/SERVICE MARK" ,
  NOTICEOFOPPOSITION ="NOTICE OF OPPOSITION" ,
  CounterStatement ="Counter-Statement" ,
  APPLICATIONFORISSUANCEOFCERTIFICATEFORTRADESERVICE ="APPLICATION FOR ISSUANCE OF CERTIFICATE FOR TRADE/SERVICE MARKS" ,
  RENEWALOFTRADESERVICEMARKS  ="RENEWAL OF TRADE/SERVICE MARKS (TO COMPEL PROPRIETORS TO RENEW AS AND WHEN DUE, REGULATION 66-70 RELATING TO RENEWALS SHOULD BE ENFORCED)" ,
  REGISTRATIONOFASSIGNMENTMERGER ="REGISTRATION OF ASSIGNMENT/MERGER WITHIN THE PRESCRIBED PERIOD" ,
  CTCOFPATENTCERTIFICATE ="(A)CTC OF PATENT CERTIFICATE" ,
  CTCOFCERTIFICATEOFINDUSTRIALDESIGN ="(A)CTC OF CERTIFICATE OF INDUSTRIAL DESIGN" ,
  RENEWALOFNONTEXTILEDESIGN ="RENEWAL OF NON-TEXTILE DESIGN" ,
  RENEWALOFTEXTILEDESIGNCERTIFICATE ="RENEWAL OF TEXTILE DESIGN CERTIFICATE" ,
  CHANGEOFNAME ="CHANGES IN REGISTERED PARTICULARS (NAMES, ADDRESSES ETC)" ,
  CHANGEOFADDRESS ="CHANGES IN REGISTERED PARTICULARS (NAMES, ADDRESSES ETC)" ,




  }
