export enum Fee2 {

  REGISTRATIONOFDESIGNSTEXTILE = "24"  ,
  REGISTRATIONOFDESIGNSNONTEXTILE = "26"  ,
  REGISTRATIONOFPATENTNONCONVENTIONAL ="19" ,
  REGISTRATIONOFPATENTCONVENTIONAL ="18",
  PRELIMINARYSEARCHREPORT ="1" ,
  APPLICATIONFORREGISTRATIONOFTRADESERVICE ="8" ,
  NOTICEOFOPPOSITION ="9" ,
  CounterStatement ="11" ,
  APPLICATIONFORISSUANCEOFCERTIFICATEFORTRADESERVICE ="13" ,
  RENEWALOFTRADESERVICEMARKS  ="15" ,
  REGISTRATIONOFASSIGNMENTMERGER ="17" ,
  CTCOFPATENTCERTIFICATE ="21" ,
  CTCOFCERTIFICATEOFINDUSTRIALDESIGN ="27" ,
  RENEWALOFNONTEXTILEDESIGN ="28" ,
  RENEWALOFTEXTILEDESIGNCERTIFICATE ="29" ,




  }
