export enum Fee2 {

  REGISTRATIONOFDESIGNSTEXTILE = "45"  ,
  REGISTRATIONOFDESIGNSNONTEXTILE = "44"  ,
  REGISTRATIONOFPATENTNONCONVENTIONAL ="29" ,
  REGISTRATIONOFPATENTCONVENTIONAL ="28",
  PRELIMINARYSEARCHREPORT ="1" ,
  APPLICATIONFORREGISTRATIONOFTRADESERVICE ="2" ,
  NOTICEOFOPPOSITION ="4" ,
  CounterStatement ="5" ,
  APPLICATIONFORISSUANCEOFCERTIFICATEFORTRADESERVICE ="3" ,
  RENEWALOFTRADESERVICEMARKS  ="9" ,
  REGISTRATIONOFASSIGNMENTMERGER ="14" ,
  CTCOFPATENTCERTIFICATE ="37" ,
  CTCOFCERTIFICATEOFINDUSTRIALDESIGN ="46" ,
  RENEWALOFNONTEXTILEDESIGN ="44" ,
  RENEWALOFTEXTILEDESIGNCERTIFICATE ="45" ,
  CHANGESINREGISTEREDPARTICULARSNAMESandADDRESSESETC ="8" ,
  ANNUALPATENTRENEWAL ="30"




  }
